---
platform: linux
image_resource:
  type: docker-image
  #todo maybe there is a more suitable docker image with haproxy+ssl?
  source:
    repository: haproxy
    tag: "1.8" # pin to same major versions that we deploy

inputs:
- name: certs.s3
- name: apps-certs.s3
- name: system-certs.s3
- name: ops.git
- name: this.git
outputs:
- name: release
run:
  path: this.git/ci/scripts/create-release.sh
params:
