---
platform: linux
image_resource:
  type: docker-image
  source: {repository: govau/cga-cf-bosh-cli}
inputs:
- name: this.git
- name: ops.git
run:
  path: this.git/ci/scripts/deploy-release.sh
params:
  ENV_NAME:
  JUMPBOX_SSH_KEY:
