groups: []
resources:
- name: ops.git
  type: git
  source:
    branch: master
    paths:
    - frontend/config-bucket/**
    private_key: {{ops-git-deploy-key}}
    uri: {{ops-git-uri}}
- name: this.git
  type: git
  source:
    branch: master
    uri: https://github.com/govau/cga-frontend-config
- name: certs-d.s3
  type: s3
  source:
    access_key_id: {{aws-access-key-id-d}}
    bucket: {{aws-bucket-d}}
    region_name: ap-southeast-2
    secret_access_key: {{aws-secret-access-key-d}}
    server_side_encryption: AES256
    versioned_file: le-responder/current-certificates.tgz
- name: certs-g.s3
  type: s3
  source:
    access_key_id: {{aws-access-key-id-g}}
    bucket: {{aws-bucket-g}}
    region_name: ap-southeast-2
    secret_access_key: {{aws-secret-access-key-g}}
    server_side_encryption: AES256
    versioned_file: le-responder/current-certificates.tgz
- name: release-d.s3
  type: s3
  source:
    access_key_id: {{aws-access-key-id-d}}
    bucket: {{aws-bucket-d}}
    region_name: ap-southeast-2
    secret_access_key: {{aws-secret-access-key-d}}
    server_side_encryption: AES256
    versioned_file: release.tgz
- name: release-g.s3
  type: s3
  source:
    access_key_id: {{aws-access-key-id-g}}
    bucket: {{aws-bucket-g}}
    region_name: ap-southeast-2
    secret_access_key: {{aws-secret-access-key-g}}
    server_side_encryption: AES256
    versioned_file: release.tgz
- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: d-cld
  plan:
  - do:
    - aggregate:
      - get: certs.s3
        trigger: true
        resource: certs-d.s3
      - get: ops.git
        trigger: true
      - get: this.git
    - task: create-release
      file: this.git/ci/tasks/create-release.yml
    - put: release-d.s3
      params:
        file: release/release.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: g-cld
  plan:
  - do:
    - aggregate:
      - get: certs.s3
        trigger: true
        resource: certs-g.s3
      - get: ops.git
        trigger: true
      - get: this.git
    - task: create-release
      file: this.git/ci/tasks/create-release.yml
    - put: release-g.s3
      params:
        file: release/release.tgz
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
